"""Canonical platform-independent models shared across the BSFAI core."""

from .device import (
    CommandExecutionResult,
    CommandExecutionStatus,
    DeviceCapabilities,
    DeviceProfile,
)
from .inventory import (
    BatteryPackIdentity,
    BindingState,
    DeviceBindingProposal,
    DeviceControlState,
    DeviceInventory,
    DiscoveryCandidate,
    MainDevice,
    NativeDeviceIdentity,
    ZendureTransport,
)
from .hems import HemsStatus
from .limits import (
    ControlBlocker,
    DirectionLimitRequest,
    EffectivePowerLimit,
    EffectiveSocLimits,
    LimitDiagnostic,
    LimitLayer,
    NamedLimit,
    NativeCommandLimits,
    NativeControlGate,
    PowerDirection,
    SocLimitRequest,
    resolve_native_command_limits,
    resolve_power_limit,
    resolve_soc_limits,
)
from .market import (
    MarketPrice,
    MarketPriceDirection,
    MarketPriceForecast,
    MarketPricePoint,
    MarketPriceValidity,
)
from .native_device_state import (
    DeviceOperatingMode,
    NeutralDeviceState,
    NeutralPackState,
    ReportedDeviceSetpoints,
)
from .regulation import (
    AutomaticStrategyResult,
    ChargeSourceAllocation,
    DeviceCommand,
    GridHistoryState,
    ModeArbiterResult,
    PowerControllerResult,
    RegulationRuntimeState,
    StrategyContext,
    StrategyIntent,
)
from .runtime import AiMode, DecisionContext, RuntimeSnapshot
from .states import (
    AdditionalBatteryState,
    BatteryState,
    GridState,
    MeasuredValue,
    OffGridState,
    PVState,
    ValueValidity,
)
from .strategy import (
    ChargeCommitState,
    StrategicState,
    StrategyDecision,
    VisibleState,
)

__all__ = [
    "AdditionalBatteryState",
    "AiMode",
    "AutomaticStrategyResult",
    "BatteryState",
    "BatteryPackIdentity",
    "BindingState",
    "ChargeCommitState",
    "ChargeSourceAllocation",
    "CommandExecutionResult",
    "CommandExecutionStatus",
    "ControlBlocker",
    "DeviceCapabilities",
    "DeviceBindingProposal",
    "DeviceControlState",
    "DeviceInventory",
    "DeviceProfile",
    "DirectionLimitRequest",
    "DeviceOperatingMode",
    "DeviceCommand",
    "DecisionContext",
    "GridHistoryState",
    "GridState",
    "HemsStatus",
    "DiscoveryCandidate",
    "EffectivePowerLimit",
    "EffectiveSocLimits",
    "MarketPrice",
    "MarketPriceDirection",
    "MarketPriceForecast",
    "MarketPricePoint",
    "MarketPriceValidity",
    "MeasuredValue",
    "MainDevice",
    "LimitDiagnostic",
    "LimitLayer",
    "ModeArbiterResult",
    "NativeDeviceIdentity",
    "NamedLimit",
    "NativeCommandLimits",
    "NativeControlGate",
    "NeutralDeviceState",
    "NeutralPackState",
    "OffGridState",
    "PVState",
    "PowerControllerResult",
    "PowerDirection",
    "RegulationRuntimeState",
    "ReportedDeviceSetpoints",
    "SocLimitRequest",
    "RuntimeSnapshot",
    "StrategicState",
    "StrategyContext",
    "StrategyDecision",
    "StrategyIntent",
    "ValueValidity",
    "VisibleState",
    "ZendureTransport",
    "resolve_native_command_limits",
    "resolve_power_limit",
    "resolve_soc_limits",
]
